# name: Build on Mac Catalyst with .NET 10 Preview
#
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#
# jobs:
#   build-maccatalyst:
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup .NET 10 Preview
#         uses: actions/setup-dotnet@v4
#         with:
#           dotnet-version: '10.0.100-preview.4'
#       - name: Restore dependencies
#         run: dotnet restore --framework net10.0-maccatalyst
#       - name: Build
#         run: dotnet build --framework net10.0-maccatalyst --configuration Release --no-restore
#       - name: Test (Mac Catalyst)
#         run: dotnet test --framework net10.0-maccatalyst --no-build || echo "Test step failed (expected for preview)"
